[functions.spd-service-telegram-notify]
verify_jwt = false

[functions.meeting-room-telegram-notify]
verify_jwt = false

[functions.export-audit-logs]
verify_jwt = false


[functions.record-audit-log]
verify_jwt = false

[functions.update-user-email]
verify_jwt = false

[functions.record-login-attempt]
verify_jwt = false

[functions.backup-restore-data]
verify_jwt = false
